version: 0.2

phases:
  build:
    commands:
      - echo "Syncing files to S3 bucket..."
      - aws s3 sync . s3://daveberriosresume.com/ --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
